-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 16:56:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fourchannel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fourchannel` ;

-- -----------------------------------------------------
-- Schema fourchannel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fourchannel` DEFAULT CHARACTER SET utf8 ;
USE `fourchannel` ;

-- -----------------------------------------------------
-- Table `fourchannel`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`pessoas` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `pessoa_idpessoa` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `fourchannel`.`pessoas` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`series` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`series` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `id_serie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`temporadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`temporadas` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`temporadas` (
  `series_idserie` INT NOT NULL,
  `serie_idserie` INT NOT NULL,
  `duracao` INT(4) NOT NULL,
  `assistido` INT(1) NOT NULL,
  INDEX `fk_temporadas_series1_idx` (`series_idserie` ASC) VISIBLE,
  CONSTRAINT `fk_temporadas_series1`
    FOREIGN KEY (`series_idserie`)
    REFERENCES `fourchannel`.`series` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`estatisticas_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`estatisticas_series` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`estatisticas_series` (
  `serie_idserie` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `assistido` INT(1) NULL,
  PRIMARY KEY (`serie_idserie`, `usuario_idusuario`),
  INDEX `fk_serie_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_serie_has_usuario_serie1_idx` (`serie_idserie` ASC) VISIBLE,
  CONSTRAINT `fk_serie_has_usuario_serie1`
    FOREIGN KEY (`serie_idserie`)
    REFERENCES `fourchannel`.`series` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `fourchannel`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`filmes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`filmes` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`filmes` (
  `idfilmes` INT NOT NULL AUTO_INCREMENT,
  `id_filme` VARCHAR(45) NOT NULL,
  `duracao` INT(4) NOT NULL,
  PRIMARY KEY (`idfilmes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fourchannel`.`estatisticas_filmes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fourchannel`.`estatisticas_filmes` ;

CREATE TABLE IF NOT EXISTS `fourchannel`.`estatisticas_filmes` (
  `filmes_idfilmes` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  `assistido` INT NOT NULL,
  PRIMARY KEY (`filmes_idfilmes`, `usuarios_idusuario`),
  INDEX `fk_filmes_has_usuarios_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_filmes_has_usuarios_filmes1_idx` (`filmes_idfilmes` ASC) VISIBLE,
  CONSTRAINT `fk_filmes_has_usuarios_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `fourchannel`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `fourchannel`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
